% -------------------------------------------------------------------
%  Generated by MATLAB on 14-Nov-2022 06:04:26
%  MATLAB version: 9.9.0.1467703 (R2020b)
% -------------------------------------------------------------------
saveVarsMat = load('f_ger_stim_onset_RF.mat');

varargin = saveVarsMat.varargin; % <1x3 cell> unsupported class at varargin{1}

clear saveVarsMat;
